# php+pgsql+redis project - POSTGRESQL DEPLOYMENT
# @maintainer G.Gatto 2021 - www.garanet.net
# repo from https://github.com/garanet/k8s-php-pgsql-redis
# Tested on a MacOsx with Docker + Kuberneters (Docker-Desktop)
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 2
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
        - name: postgresql-db
          image: postgres:latest
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "psql -h localhost -U testdbuser -d testdb -f /dump/employee.sql"]
            preStop:
              exec:
                command:
                  - sh
                  - '-c'
                  - sleep 5 && kill -SIGQUIT 1  
          volumeMounts:
            - name: postgresql-db-disk
              mountPath: /data
            - name: postgresql-dump
              mountPath: /dump
          envFrom:
          - configMapRef:
              name: postgres-db-config
      volumes:
        - name: postgresql-dump
          configMap:
            name: postgresql-dump
  volumeClaimTemplates:
    - metadata:
        name: postgresql-db-disk
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 25Gi