# php+pgsql+redis project - POSTGRESQL SECRET
# @maintainer G.Gatto 2021 - www.garanet.net
# repo from https://github.com/garanet/k8s-php-pgsql-redis
# Tested on a MacOsx with Docker + Kuberneters (Docker-Desktop)
apiVersion: v1
kind: Secret
metadata:
  name: postgres
data:
  POSTGRES_PASSWORD: c2VjcmV0LXBhc3N3b3Jk 
stringData:
  POSTGRES_USER: root
