# php+pgsql+redis project - NGINX CONFIG
# @maintainer G.Gatto 2021 - www.garanet.net
# repo from https://github.com/garanet/k8s-php-pgsql-redis
# Tested on a MacOsx with Docker + Kuberneters (Docker-Desktop)
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
    }
    http {
      server {
        listen 80 default_server;
        listen [::]:80 default_server;
        # Set nginx to serve files from the shared volume!
        root /var/www/html;
        server_name _;
        index index.php;
        location / {
          include  /etc/nginx/mime.types;
          try_files $uri /index.php?$query_string;
        }
        location = /favicon.ico { log_not_found off; access_log off; }
        location = /robots.txt  { access_log off; log_not_found off; }
        sendfile off;
        client_max_body_size 100m;
        location ~ \.php$ {
          include fastcgi_params;
          fastcgi_index index.php;
          fastcgi_param REQUEST_METHOD $request_method;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_pass 127.0.0.1:9000;
        }
      }
    }