# php+pgsql+redis project - REDIS SECRET
# @maintainer G.Gatto 2021 - www.garanet.net
# repo from https://github.com/garanet/k8s-php-pgsql-redis
# Tested on a MacOsx with Docker + Kuberneters (Docker-Desktop)
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
data:
  REDIS_PASS: cmVkaXMtcGFzc3dvcmQ=
